config/routes.rb
P2fx::Application.routes.draw do
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :sips
      


  match '/search', to: 'sips#search'
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  authenticated :user do
    root :to => "sips#index"
  end
  root :to => "sips#index"












end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://techytom.com/">p2fxweb</a>
    by Tomiwa Ijaware
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://iqubebase.com/">IqubeBase</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">      
      <nav>
      	<%= link_to "p2fx", root_path, id: "logo" %>
        <ul class="nav pull-right">
          <li><form class="navbar-search pull-left"><input type="text" class="search-query" placeholder="Search"></form></li>          
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in_user %>
            <li><%= link_to "Users", users_path %></li>
            <li class="divider-vertical"></li>
            <li id="fat-menu" class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Location <b class="caret"></b></a>
            	<ul class="dropdown-menu">
            		<li><a href= "#" class="button" id="getLoc">Current Location</a></li>
            		<li><a href= "#" class="button" id="setLoc">Set Location</a></li>
            	</ul>            	
            </li>
            <li class="divider-vertical"></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Upload Sip", new_sip_path(current_user) %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>
    <%= javascript_include_tag "application" %>    
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>